// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManager.DataAccess;

namespace TaskManager.DataAccess.Migrations
{
    [DbContext(typeof(TaskManagerContext))]
    [Migration("20210220225328_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TaskManager.DataAccess.Entities.Assignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BoardId")
                        .HasColumnType("int");

                    b.Property<int?>("BoardId1")
                        .HasColumnType("int");

                    b.Property<int?>("BoardId2")
                        .HasColumnType("int");

                    b.Property<int?>("BoardId3")
                        .HasColumnType("int");

                    b.Property<int?>("BoardId4")
                        .HasColumnType("int");

                    b.Property<int?>("BoardId5")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeadlineTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tilte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssignmentId");

                    b.HasIndex("BoardId");

                    b.HasIndex("BoardId1");

                    b.HasIndex("BoardId2");

                    b.HasIndex("BoardId3");

                    b.HasIndex("BoardId4");

                    b.HasIndex("BoardId5");

                    b.HasIndex("CustomerId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("TaskManager.DataAccess.Entities.Board", b =>
                {
                    b.Property<int>("BoardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("BoardId");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("TaskManager.DataAccess.Entities.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommentId");

                    b.HasIndex("AssignmentId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("TaskManager.DataAccess.Entities.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("TaskManager.DataAccess.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("TaskManager.DataAccess.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Password")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TaskManager.DataAccess.Entities.Manager", b =>
                {
                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Password")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ManagerId");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("TaskManager.DataAccess.Entities.Assignment", b =>
                {
                    b.HasOne("TaskManager.DataAccess.Entities.Board", "Board")
                        .WithMany("ToBePlanned")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManager.DataAccess.Entities.Board", null)
                        .WithMany("Canceled")
                        .HasForeignKey("BoardId1");

                    b.HasOne("TaskManager.DataAccess.Entities.Board", null)
                        .WithMany("Completed")
                        .HasForeignKey("BoardId2");

                    b.HasOne("TaskManager.DataAccess.Entities.Board", null)
                        .WithMany("InProgress")
                        .HasForeignKey("BoardId3");

                    b.HasOne("TaskManager.DataAccess.Entities.Board", null)
                        .WithMany("Planned")
                        .HasForeignKey("BoardId4");

                    b.HasOne("TaskManager.DataAccess.Entities.Board", null)
                        .WithMany("Suspended")
                        .HasForeignKey("BoardId5");

                    b.HasOne("TaskManager.DataAccess.Entities.Customer", "Customer")
                        .WithMany("AssignmentList")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("TaskManager.DataAccess.Entities.Comment", b =>
                {
                    b.HasOne("TaskManager.DataAccess.Entities.Assignment", "Assignment")
                        .WithMany("CommentsList")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("TaskManager.DataAccess.Entities.Employee", b =>
                {
                    b.HasOne("TaskManager.DataAccess.Entities.Company", "Company")
                        .WithMany("EmployeesList")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManager.DataAccess.Entities.Board", "Board")
                        .WithOne("Employee")
                        .HasForeignKey("TaskManager.DataAccess.Entities.Employee", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("TaskManager.DataAccess.Entities.Manager", b =>
                {
                    b.HasOne("TaskManager.DataAccess.Entities.Company", "Company")
                        .WithOne("Manager")
                        .HasForeignKey("TaskManager.DataAccess.Entities.Manager", "ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("TaskManager.DataAccess.Entities.Assignment", b =>
                {
                    b.Navigation("CommentsList");
                });

            modelBuilder.Entity("TaskManager.DataAccess.Entities.Board", b =>
                {
                    b.Navigation("Canceled");

                    b.Navigation("Completed");

                    b.Navigation("Employee")
                        .IsRequired();

                    b.Navigation("InProgress");

                    b.Navigation("Planned");

                    b.Navigation("Suspended");

                    b.Navigation("ToBePlanned");
                });

            modelBuilder.Entity("TaskManager.DataAccess.Entities.Company", b =>
                {
                    b.Navigation("EmployeesList");

                    b.Navigation("Manager")
                        .IsRequired();
                });

            modelBuilder.Entity("TaskManager.DataAccess.Entities.Customer", b =>
                {
                    b.Navigation("AssignmentList");
                });
#pragma warning restore 612, 618
        }
    }
}
